# Generated by Django 5.2.4 on 2025-07-15 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=15)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("merchant_request_id", models.CharField(max_length=100)),
                ("checkout_request_id", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=20)),
                ("description", models.TextField(blank=True)),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("subscription", "Subscription"),
                            ("post_job", "Post Job"),
                            ("post_ad", "Post Ad"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("post_expiry_date", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
