# Generated by Django 5.2.4 on 2025-07-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_purpose_alter_payment_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('fundi_subscription', 'Fundi Subscription'), ('client_post_job', 'Client Post Job'), ('client_post_ad', 'Client Post Ad')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
