# Generated by Django 5.2.4 on 2025-07-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_purpose_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='post_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('subscription', 'Subscription'), ('post_job', 'Post Job'), ('post_ad', 'Post Ad')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
