# Generated by Django 5.2.4 on 2025-07-08 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_is_active'),
        ('payments', '0004_payment_post_expiry_date_alter_payment_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
