# Generated by Django 5.2.4 on 2025-07-07 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundiProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('show_contact', models.BooleanField(default=True)),
                ('rate_note', models.TextField(blank=True, help_text='e.g. Ksh 1500/day, negotiable')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundi_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
