# Generated by Django 5.2.4 on 2025-07-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_clientprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
