# Generated by Django 5.2.4 on 2025-07-11 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_subscription_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='on_trial',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='trial_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
