# Generated by Django 5.2.4 on 2025-07-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_on_trial_user_trial_ends_user_trial_started'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='on_trial',
        ),
        migrations.RemoveField(
            model_name='user',
            name='subscription_end',
        ),
    ]
