# Generated by Django 5.2.4 on 2025-07-13 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_remove_user_on_trial_remove_user_subscription_end"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription_override",
            field=models.BooleanField(
                default=False, help_text="Set True to simulate active subscription"
            ),
        ),
    ]
