# Generated by Django 5.2.4 on 2025-07-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_user_subscription_override"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscription_override",
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
